version: "3.1"

services:
  api:
    container_name: api
    build:
      context: .
    command: npm run start
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=test-union
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: